apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"