apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: ns-postgresql
subjects:
- kind: ServiceAccount
  name: default
  namespace: ns-spring-boot
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
