apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  password: bGlua2V5YWRtaW4xMiE=  # "linkeyadmin12!"의 base64
  username: bGluay1hZG1pbg==  # "linkeyadmin"의 base64
  dbname: bGluay1kZXYtZGF0YWJhc2U=  # "linkey-dev-database"의 base64