apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  password: bGlua2V5YWRtaW4xMiE=  # "linkeyadmin12!"의 base64
  username: bGlua2V5YWRtaW4=  # "linkeyadmin"의 base64
  dbname: bGlua2V5  # "linkey"의 base64