apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: default
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 33000
  type: NodePort