apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: ns-react
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      nodeSelector:
        app-node: "true"
      containers:
        - name: react
          image: linkeydockerhub/react-app:9aba50e
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
