apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ns-redis
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      # nodeSelector:
      #   db-node: "true"
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379