apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-service:5432/linkey"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"  # 스키마 변경 방지 (필요시 update로 변경)
  SPRING_JPA_SHOW_SQL: "true"  # SQL 로그 출력
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
