apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: ns-spring-boot
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      nodeSelector:
        app-node: "true"
      containers:
      - name: spring-boot
        image: linkeydockerhub/spring-boot-app:1f0d27a
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgresql-service.ns-postgres.svc.cluster.local:5432/${POSTGRES_DB}"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: dbname
              optional: true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
                name: postgresql-secret
                key: username
                optional: true
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
              optional: true
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"