apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-pvc
  namespace: ns-spring-boot
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
