apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: default
spec:
  selector:
    app: spring-boot
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8080
  type: NodePort 