apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  - port: 443
    targetPort: 443
    nodePort: 30443
  selector:
    app: nginx-ingress-controller
