apiVersion: v1
kind: Secret
metadata:
  name: redis-acl
  namespace: default
type: Opaque
data:
  users.acl: |
    ZGVmYXVsdCBvbiArQGFsbA==   # "default on +@all"
    bGlua2V5YWRtaW4gb24gK0BhbGw=  # "linkeyadmin on +@all"
