apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ns-redis
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        db-node: "true"
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: username
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        command:
          - sh
          - -c
          - |
            sed "s/%USERNAME%/$REDIS_USERNAME/; s/%PASSWORD%/$REDIS_PASSWORD/" /etc/redis/redis.acl > /tmp/redis.acl && \
            redis-server --aclfile /tmp/redis.acl
      volumes:  
      - name: redis-config  
        configMap:
          name: redis-config