apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: ns-redis
spec:
  encryptedData:
    password: AgCsCD2cQMMWv8FiG22nvTqa72LsTuNpVdr/Je9oBuNaUvLmUtdxtwGr09NJ7YXATQHDwbA3S/p+MFqgnnC+hGfsxeydAUukYC0vNtv3ixrn1m5EvFVO61wu1aUjjjUZ1M4jaTsGxUiNPn59owDFdYDqxhPfViN9WTWht1KAy5dWsrRbB9d7bsXO+FWTHElOmTeBlzO4uR5CkTQDj/0FZvaz4MuffV8qkqkJwqlsVIjgpG3nSnRVUjOi9oXkmc7SZsEsmYZTXNKSHxPOSCjtFvJ53/Ai0tmwkCIFvWkQxigMAquqR7t+3v4LNrP+YOTpGBiSCXbmC4gmHqRrB/EHJw5TK1g4hKoOjRmDyfcQkcOiQBMq+ZPSE/iRmyNFcKlbW0aC/RTkRIgghq3R2z0qlCNxwtcT056HXO8s/wHpuLbCRznW0IC7iv09fAQCriZiMTJlKOvKgjur4jh5d86FlpIZkcPlV68om7GnlBcV49+rfan8dUMQJL2kJFDktiAg+ZFMARQesCf7fvZvSi6QtNKBjn566lHn+YAe5lMchk8B7nUuxo2om1Q10hJapf+aJIgfpYioCP50rmolO4bN9NVXRsA+DxD4rLRpYeoTx3+C0ThP8OR8gkivQh/YkzbuFVtYDfHaCZ3dFhi3/9/6sXLYFLJuGSUS9/EA8wAfkUS2V8zSqvU/sjDxEi7Ee/F+6E+ikKn20hIbEaq3Px3AMTlEuPZZ61fDfOM6B9pAVB8k+kDhySpuop+a0JHoL8XXHB0=
    username: AgACouClMHWRjeo5zhlxOogivIS8Dpxn+a1EVE/uc+reOyuIesBlOm7m3tByqSmSs1gP/XaQNSeKdURQMmfA3fzYcCPkAQC6RqSdu9u+o+5IYDcR12wDHmRFSbTeKhSo+ObcJrDpElb5S943Wo4HNtHJD+nvM4gVjvw/rNV0JelUnNutFZ3NnTRirPsqiRZcTn1ZxN+t8MZEwCNq4Z/9Fx4jB8uLPwG8cSyE9r8C0yvDOOSfF9q9hxq2yUx89s7tziWtrAU1gylHJXxklmWFltx8NYxLJlHc+XYoTXwmqdeDIDdHJ4Li6zEj2II5F+mYU+/5yM983hlEf4L394kTs/kIYOpiT7GU+CvfJWbzlcygmuAvi8TtGKSugonicXiJxiSKCyeSCqg5TTs2AvpGoDd/4dJj54NP+jb/jLU0LZvHtSzjzHLGwDAI9LWe18mPQwuMSsgwwpOPBNJYOwIsFaHER+Y/d20PpzIct6I0ane+EdhkGa2U5TO6EsuK6Tj0XCyScDsOTwDQlizCFLSV5cdStkUmGYo5TOJPn2JB9FYfJK2WnIBpfZDWrGPDNBu7MJxg8CiUQye7EUKn+d1gA3oXpzbLKDZtJ9AosvdUTzk2HzMCzkWPYXjsGwtnUoK2yiFr/ZV4fpyXmjYTziFgkDC4FttTwYgC1TNTn+4WHOyHV+mqbdt1vx/SXOVbnrBLoeAf2hIg75buRJYz/67GDDOKenGkSJs3bngwXGldjTbp4ZofOyeRJ93Iwm+N3OcPbAw=
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: ns-redis
    type: Opaque